/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudpoo;

import crudpoo.clases.Conexion;
import crudpoo.clases.Vehiculos;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblNumeroRuedas = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblTipoVehiculo = new javax.swing.JLabel();
        lblTtitleTipoVehiculo1 = new javax.swing.JLabel();
        lblTtitleColor1 = new javax.swing.JLabel();
        lblTtitleNumeroRuedas1 = new javax.swing.JLabel();
        lblTtitlePlaca1 = new javax.swing.JLabel();
        lblTtitleUsuario1 = new javax.swing.JLabel();
        lblTtitleId1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBuscarPlaca.setText("Placa: ");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("Busqueda por Placa");

        lblId.setText("Id");

        lblUsuario.setText("Usuario");

        lblPlaca.setText("Placa");

        lblNumeroRuedas.setText("Número de Ruedas");

        lblColor.setText("Color");

        lblTipoVehiculo.setText("tipo Vehiculo");

        lblTtitleTipoVehiculo1.setText("tipo Vehiculo");

        lblTtitleColor1.setText("Color");

        lblTtitleNumeroRuedas1.setText("Número de Ruedas");

        lblTtitlePlaca1.setText("Placa");

        lblTtitleUsuario1.setText("Usuario");

        lblTtitleId1.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTtitleId1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTtitleUsuario1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTtitlePlaca1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTtitleNumeroRuedas1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTtitleColor1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTtitleTipoVehiculo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(lblPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumeroRuedas)
                        .addGap(18, 18, 18)
                        .addComponent(lblColor)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoVehiculo)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTtitleId1)
                    .addComponent(lblTtitleUsuario1)
                    .addComponent(lblTtitlePlaca1)
                    .addComponent(lblTtitleNumeroRuedas1)
                    .addComponent(lblTtitleColor1)
                    .addComponent(lblTtitleTipoVehiculo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblUsuario)
                    .addComponent(lblPlaca)
                    .addComponent(lblNumeroRuedas)
                    .addComponent(lblColor)
                    .addComponent(lblTipoVehiculo))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblBuscarPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        String placa = txtPlaca.getText();

        int id = 0;
        String usuario = "";
        String placa2 = "";
        int numeroRuedas = 0;
        String color = "";
        String tipoVehiculo = "";
        try {
            if (!placa.isEmpty()) {
                ArrayList<Vehiculos> listaVehiculos = con.buscarPorPlaca(placa);
                if (listaVehiculos != null) {
                    for (Vehiculos vehiculo : listaVehiculos) {
                        id = vehiculo.getIdVehiculo();
                        usuario = vehiculo.getNombreCompleto();
                        placa2 = vehiculo.getPlaca();
                        numeroRuedas = vehiculo.getNumeroRuedas();
                        color = vehiculo.getColor();
                        tipoVehiculo = vehiculo.getTipoVehiculo();
                    }
                    this.lblId.setText(String.valueOf(id));
                    this.lblUsuario.setText(usuario);
                    this.lblPlaca.setText(placa2);
                    this.lblNumeroRuedas.setText(String.valueOf(numeroRuedas));
                    this.lblColor.setText(color);
                    this.lblTipoVehiculo.setText(tipoVehiculo);
                }else{
                     JOptionPane.showMessageDialog(null, "No se han encontrado registros!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No ha ingresado valores correctos!");
            }
        } catch (SQLException ex) {

        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuscarPlaca;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNumeroRuedas;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTipoVehiculo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTtitleColor1;
    private javax.swing.JLabel lblTtitleId1;
    private javax.swing.JLabel lblTtitleNumeroRuedas1;
    private javax.swing.JLabel lblTtitlePlaca1;
    private javax.swing.JLabel lblTtitleTipoVehiculo1;
    private javax.swing.JLabel lblTtitleUsuario1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
