/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudpoo;

import crudpoo.clases.Conexion;
import crudpoo.clases.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author carlo
 */
public class parqueadero extends javax.swing.JFrame {

    /**
     * Creates new form registroCarros
     */
    public parqueadero() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    ArrayList<Usuario> users = new ArrayList<>();

    public void setDatosUsuarios(ArrayList<Usuario> users) {
        if (!users.isEmpty()) {
            users.forEach(user -> {
                this.users.add(user);
                //System.out.println(user);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarVehiculos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarVehiculos = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnRegistroUsuarios = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        btnRegistroAdmins = new javax.swing.JButton();
        btnEliminarVehiculos = new javax.swing.JButton();
        btnGenerarRecibo = new javax.swing.JButton();
        lblSesion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarVehiculos.setText("Agregar Vehiculos");
        btnAgregarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVehiculosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("PARQUEADERO");

        btnBuscarVehiculos.setText("Buscar Vehiculos");
        btnBuscarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculosActionPerformed(evt);
            }
        });

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnRegistroUsuarios.setText("Registro de Usuarios");
        btnRegistroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsuariosActionPerformed(evt);
            }
        });

        btnModificarDatos.setText("Modificar Datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });

        btnRegistroAdmins.setText("Registro de Administradores");
        btnRegistroAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAdminsActionPerformed(evt);
            }
        });

        btnEliminarVehiculos.setText("Eliminar Vehiculos");
        btnEliminarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVehiculosActionPerformed(evt);
            }
        });

        btnGenerarRecibo.setText("Generar Recibo");
        btnGenerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReciboActionPerformed(evt);
            }
        });

        lblSesion.setText("Sesion iniciada como: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistroAdmins)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistroUsuarios))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAtras)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnAgregarVehiculos)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarRecibo)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarVehiculos)
                    .addComponent(btnBuscarVehiculos)
                    .addComponent(btnModificarDatos)
                    .addComponent(btnEliminarVehiculos)
                    .addComponent(btnGenerarRecibo))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroUsuarios)
                    .addComponent(btnRegistroAdmins)
                    .addComponent(lblSesion)
                    .addComponent(lblNombre))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVehiculosActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        registroVehiculos v = new registroVehiculos();
        try{
        v.setComboBoxUsuarios(con.traerUsuarios());
        v.setVisible(true);
        }catch(SQLException ex){
            
        }
        
    }//GEN-LAST:event_btnAgregarVehiculosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsuariosActionPerformed
        // TODO add your handling code here:
        registro rg = new registro();
        rg.disableButton();
        rg.setVisible(true);
        
    }//GEN-LAST:event_btnRegistroUsuariosActionPerformed

    private void btnBuscarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculosActionPerformed
        // TODO add your handling code here:
        Buscar b = new Buscar();
        b.setVisible(true);
    }//GEN-LAST:event_btnBuscarVehiculosActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        // TODO add your handling code here:
        Modificar m = new Modificar();
        m.setVisible(true);
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnRegistroAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAdminsActionPerformed
        // TODO add your handling code here:
        registro rg = new registro();
        rg.cambiarCargo("Admin");
        rg.disableButton();
        rg.setVisible(true);
    }//GEN-LAST:event_btnRegistroAdminsActionPerformed

    private void btnEliminarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVehiculosActionPerformed
        // TODO add your handling code here:
        Eliminar e = new Eliminar();
        e.setVisible(true);
    }//GEN-LAST:event_btnEliminarVehiculosActionPerformed

    private void btnGenerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReciboActionPerformed
        // TODO add your handling code here:
        Recibo r = new Recibo();
        r.setVisible(true);
    }//GEN-LAST:event_btnGenerarReciboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parqueadero().setVisible(true);
            }
        });
    }
    
    public void setNombreSesion(String nombre){
        this.lblNombre.setText(nombre);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVehiculos;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarVehiculos;
    private javax.swing.JButton btnEliminarVehiculos;
    private javax.swing.JButton btnGenerarRecibo;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnRegistroAdmins;
    private javax.swing.JButton btnRegistroUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSesion;
    // End of variables declaration//GEN-END:variables
}
