/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudpoo;

import crudpoo.clases.Conexion;
import crudpoo.clases.Vehiculos;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class Recibo extends javax.swing.JFrame {

    /**
     * Creates new form Recibo
     */
    public Recibo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblTitleDatos = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblTipoVehiculo = new javax.swing.JLabel();
        txtTipoVehiculo = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        lblPlacaE = new javax.swing.JLabel();
        txtPlacaE = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        CBPrecioPorHora = new javax.swing.JComboBox<>();
        lblCantidadHoras = new javax.swing.JLabel();
        txtCantidadHoras = new javax.swing.JTextField();
        lblPrecioxHora = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("RECIBO");

        lblPlaca.setText("Placa:");

        lblTitleDatos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitleDatos.setText("-------------------------------------DATOS ENCONTRADOS------------------------------------");

        btnBuscar.setText(" BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtUsuario.setEnabled(false);

        lblUsuario.setText("Usuario:");

        lblTipoVehiculo.setText("Tipo Vehiculo:");

        txtTipoVehiculo.setEnabled(false);

        lblColor.setText("Color:");

        lblPlacaE.setText("Placa:");

        txtPlacaE.setEnabled(false);

        txtColor.setEnabled(false);

        CBPrecioPorHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "2000", "3000" }));

        lblCantidadHoras.setText("Cantidad Horas:");

        lblPrecioxHora.setText("Precio por hora:");

        btnGenerar.setText("GENERAR COBRO");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitleDatos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioxHora)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTipoVehiculo)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblColor)
                                    .addComponent(lblPlacaE)
                                    .addComponent(lblCantidadHoras))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGenerar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUsuario)
                                        .addComponent(txtTipoVehiculo)
                                        .addComponent(txtPlacaE)
                                        .addComponent(txtColor)
                                        .addComponent(CBPrecioPorHora, 0, 160, Short.MAX_VALUE)
                                        .addComponent(txtCantidadHoras)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnBuscar)
                .addGap(28, 28, 28)
                .addComponent(lblTitleDatos)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlacaE)
                    .addComponent(txtPlacaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVehiculo)
                    .addComponent(txtTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColor)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadHoras)
                            .addComponent(txtCantidadHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(CBPrecioPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPrecioxHora))
                .addGap(36, 36, 36)
                .addComponent(btnGenerar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        try {
            String placa = txtPlaca.getText();
            if (!placa.isEmpty()) {
                ArrayList<Vehiculos> listaVehiculos = con.buscarPorPlaca(placa);
                if (listaVehiculos != null) {
                    listaVehiculos.forEach(vehiculo -> {
                        txtUsuario.setText(vehiculo.getNombreCompleto());
                        txtTipoVehiculo.setText(vehiculo.getTipoVehiculo());
                        txtPlacaE.setText(vehiculo.getPlaca());
                        txtColor.setText(vehiculo.getColor());
                    });
                }
            }
        } catch (SQLException ex) {
            System.out.println("SQLException:  " + ex.getMessage());
            System.out.println("SQLState:  " + ex.getSQLState());
            System.out.println("VendorError:  " + ex.getErrorCode());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        try {

            int cantidadHoras = Integer.parseInt(txtCantidadHoras.getText());
            if (cantidadHoras > 0) {
                int seleccionPrecio = Integer.parseInt(CBPrecioPorHora.getSelectedItem().toString());
                //creamos un objeto de conexion
                Conexion con = new Conexion();
                try {
                    String usuario = txtUsuario.getText();
                    String placa = txtPlacaE.getText();
                    String tipoVehiculo = txtTipoVehiculo.getText();
                    String color = txtColor.getText();
                    cantidadHoras = Integer.parseInt(txtCantidadHoras.getText());
                    int cantidadTotal = cantidadHoras * seleccionPrecio;
                    con.enviarReciboDePago(usuario, placa, tipoVehiculo, color, cantidadHoras, seleccionPrecio, cantidadTotal);
                    JOptionPane.showMessageDialog(null, "El precio a pagar por el vehiculo es: " + (cantidadHoras * seleccionPrecio));
                } catch (SQLException ex) {
                    System.out.println("SQLException:  " + ex.getMessage());
                    System.out.println("SQLState:  " + ex.getSQLState());
                    System.out.println("VendorError:  " + ex.getErrorCode());
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Has ingresado un valor erroneo!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ha ingresado una cantidad de horas erroneo! ");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Has ingresado un valor erroneo!");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPrecioPorHora;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel lblCantidadHoras;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlacaE;
    private javax.swing.JLabel lblPrecioxHora;
    private javax.swing.JLabel lblTipoVehiculo;
    private javax.swing.JLabel lblTitleDatos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCantidadHoras;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPlacaE;
    private javax.swing.JTextField txtTipoVehiculo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
